# ./.github/workflows/publish.yml
name: Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # TODO: use npm ci
      - name: Install dependencies
        run: npm install

      - name: Publish packages
        run: npx nx run-many -t build && npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CI_TOKEN }}
