name: Release package

on:
  push:
    branches:
      - main
  workflow_dispatch: # allow manual trigger

jobs:
  release:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npx nx build ngx-device-permission

      - name: Create package release
        run: npx nx release --skip-publish

      - name: Publish package
        run: npx nx publish ngx-device-permission
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CI_TOKEN }}
